#!/bin/sh

echo '---------- build env:'
#env
vars="PUSH HOSTNAME SHLVL HOME PYTHONUNBUFFERED BUILD_CODE DOCKER_TAG GIT_SHA1 GIT_MSG SOURCE_BRANCH PATH DOCKER_REPO COMMIT_MSG BUILD_PATH SOURCE_TYPE DOCKERFILE_PATH PWD IMAGE_NAME"
other_vars="DOCKER_HOST MAX_LOG_SIZE CACHE_TAG SIGNED_URLS DOCKERCFG"

for v in $vars
do echo "$v: $(eval echo \"\$$v\")"; done

echo '----------'

# highland builder does not obey skip tag
case "$COMMIT_MSG" in
  *"[skip ci]"* | *"[ci skip]"* )
    echo "Skipping build by ci-skip commit message"
    exit 1 ;;
esac

test -n "$WORKSPACE" || {
  test -n "$BUILD_CODE" && {
    export WORKSPACE=/src/$BUILD_CODE
  }
}

test -n "$WORKSPACE" || {
  test -n "$BUILD_PATH" && {
    to_workspace=./$(printf -- "$BUILD_PATH" | cut -c2- | sed 's/[^/]*/../g')
    export WORKSPACE=$(cd $to_workspace && pwd)
  }
}

echo WORKSPACE: $WORKSPACE
echo '--------------- loading env'
test -e ../env.sh && {
  . ./../env.sh
} || {
  . $WORKSPACE/tools/build-env.sh
}

xtra=
test ! -e ../build-args.sh || {
  xtra="$(grep '=' ../build-args.sh | sed 's/.*/--build-arg & \\/')"
}

echo '--------------- starting build'
docker build $xtra \
		--build-arg X_DCKR_PREFIX=$ONAME \
		--build-arg X_DCKR_BASENAME=$LNAME \
		--build-arg X_DCKR_NAME=$ONAME/$LNAME \
    --build-arg X_DCKR_TAG=$DOCKER_TAG \
    --build-arg BUILD_CODE=$BUILD_CODE \
    --build-arg IMAGE_NAME=$IMAGE_NAME \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    --build-arg SCM_TYPE=$SOURCE_TYPE \
    --build-arg GIT_BRANCH=$SOURCE_BRANCH \
    --build-arg GIT_COMMIT=$GIT_SHA1 \
    -t $IMAGE_NAME .


#echo '--------------- publishing results'
#pip install couchapp
##COUCH_DB=$(  )
#mkdir -vp build/couch/build-log
#(
#  cd build/couch/build-log
#  echo '{"env":{"default":{"db":"'$COUCH_DB'"}}}'>.couchapprc
#  couchapp pushdocs
#)


# Id: x-docker/
