#!/usr/bin/env bash

_cmd=$_

. ./../../tools/env.sh


# build is the third build-hook; See doc/dev.md
# This is the first phase of pipeline, before test and push.

echo "---------- build env: "$(pwd)
echo "Hook Cmd: $_cmd"
echo "Shell PID: $$"
echo "Shell options: $-"
#env
#echo '------'
vars="PUSH HOSTNAME SHLVL HOME PYTHONUNBUFFERED BUILD_CODE DOCKER_TAG DOCKER_TAGS GIT_SHA1 GIT_MSG SOURCE_BRANCH PATH DOCKER_REPO COMMIT_MSG BUILD_PATH SOURCE_TYPE SCM_TYPE DOCKERFILE_PATH PWD IMAGE_NAME"
other_vars="DOCKER_HOST MAX_LOG_SIZE CACHE_TAG SIGNED_URLS DOCKERCFG"

for v in $vars
do echo "$v: $(eval echo \"\$$v\")"; done
#echo '---------- exported env'
#env
#echo '---------- typeset vars'
#set | grep '^[A-Za-z0-9_-]*='
echo '----------'


# Load args at relative location

xtra=
test ! -e ./build-args.sh || {
  echo "--------------- Extra build-args"
  xtra="$(grep '^[^\#]*=' ./build-args.sh | sed 's/.*/--build-arg & /')"
}

test -n "${DOCKER_TAGS:-}" || {
  echo "Error, no Docker-Tags." >&2
  exit 1
}


echo "--------------- Starting build '${IMAGE_NAME:-}'"
BUILD_DATE="$(date --rfc-3339=seconds)"

eval "docker build $xtra \
		--build-arg X_DCKR_PREFIX=$ONAME \
		--build-arg X_DCKR_BASENAME=$LNAME \
		--build-arg X_DCKR_NAME=$ONAME/$LNAME \
    --build-arg X_DCKR_BASETAG=$X_DCKR_BASETAG \
    --build-arg X_DCKR_AI_TIME=\"$X_DCKR_AI_TIME\" \
    --build-arg X_DCKR_CI_TIME=\"$X_DCKR_CI_TIME\" \
    --build-arg X_DCKR_RELEASE=\"x-docker/$SOURCE_BRANCH $DOCKER_TAG ($VERSION) $SCM_TYPE:$GIT_SHA1 $BUILD_DATE\" \
    --build-arg BUILD_CODE=\"$BUILD_CODE\" \
    --build-arg IMAGE_NAME=\"$IMAGE_NAME\" \
    --build-arg DOCKER_TAGS=\"$DOCKER_TAGS\" \
    --build-arg DOCKER_TAG=\"$DOCKER_TAG\" \
    --build-arg SOURCE_TYPE=$SOURCE_TYPE \
    --build-arg SOURCE_BRANCH=\"$SOURCE_BRANCH\" \
    --build-arg GIT_SHA1=\"$GIT_SHA1\" \
    --build-arg COMMIT_MSG=\"$COMMIT_MSG\" \
    --build-arg BUILD_DATE=\"$BUILD_DATE\" \
    --build-arg VERSION=\"$VERSION\" \
    \
    -t $IMAGE_NAME ."


echo "--------------- Tagging '$DOCKER_TAGS'"

echo $DOCKER_TAGS | tr -s ', ' ' ' | tr ' ' '\n' | while read tag
do
  # test -n "$tag" || continue

  echo "docker tag '$IMAGE_NAME' '$DOCKER_REPO:$tag'" >&2
  docker tag $IMAGE_NAME $DOCKER_REPO:$tag
done

# TODO: couch or (l)edge container #echo '--------------- publishing results'
#pip install couchapp
##COUCH_DB=$(  )
#mkdir -vp build/couch/build-log
#(
#  cd build/couch/build-log
#  echo '{"env":{"default":{"db":"'$COUCH_DB'"}}}'>.couchapprc
#  couchapp pushdocs
#)

# Id: x-docker/0.0.2-dev tools/hooks/build
