#!/usr/bin/env bash

_cmd=$_

. ./../../tools/env.sh


# post-checkout is the first build-hook; See doc/dev.md

echo '---------- post_checkout '$(pwd)
echo "Term: $TERM"
echo "Shell: $SHELL"
echo "Shell Cmd: '$0' '$*'"
echo "Post-Checkout Hook Cmd: $_cmd"
echo "Shell PID: $$"
echo "Shell options: $-"

curl -sSf -X POST \
  "https://dotmpe.com/build.php?i=${BUILD_KEY}&SCM_REF=$GIT_SHA1&BUILD_ID=${BUILD_CODE}&START=$(urlsafe_datetime)&SCM_CT=$(urlsafe_datetime "$X_DCKR_CI_TIME")&SCM_AT=$(urlsafe_datetime "$X_DCKR_AI_TIME")"

test "$GIT_SHA1" = "$( git rev-parse HEAD )"  || {
  echo "Illegal env"
  exit 1
}


# Id: x-docker/0.0.2-dev tools/hooks/post_checkout
