#!/usr/bin/env bash

_cmd=$_

. ./../../tools/env.sh


# push is the ninth and last build-hook; See doc/dev.md for all hooks
# This is the third phase of pipeline, after build and test.


echo "---------- push '$(pwd)'"

test -n "$DOCKER_TAGS" || {
  echo "Error, no Docker-Tags." >&2
  exit 1
}

echo $DOCKER_TAGS | tr -s ', ' ' ' | tr ' ' '\n' | while read tag
do
  # test -n "$tag" || continue

  echo "docker push $DOCKER_REPO:$tag" >&2
  docker push $DOCKER_REPO:$tag
done


curl -X POST \
  https://hooks.microbadger.com/images/dotmpe/basebox/MzwGjG3Jh-gkuiy9gq4ybDVhpfk=


# Id: x-docker/0.0.2-dev tools/hooks/push
