#!/bin/sh

# test is the sixth build-hook; See doc/dev.md
# This is the second phase of pipeline, between test and push.

test ! -e ../test.sh && true || {
  . ./../test.sh || {

    case "$DOCKER_TAG" in "*-dev" ) true ;; * ) false ;; esac
  }
}
