#!/bin/sh
_cmd=$_

# build is the third build-hook; See doc/dev.md
# This is the first phase of pipeline, before test and push.

echo "---------- build env: "$(pwd)
echo "Hook Cmd: $_cmd"
echo "Shell PID: $$"
echo "Shell options: $-"
#env
#echo '------'
vars="PUSH HOSTNAME SHLVL HOME PYTHONUNBUFFERED BUILD_CODE DOCKER_TAG GIT_SHA1 GIT_MSG SOURCE_BRANCH PATH DOCKER_REPO COMMIT_MSG BUILD_PATH SOURCE_TYPE DOCKERFILE_PATH PWD IMAGE_NAME"
other_vars="DOCKER_HOST MAX_LOG_SIZE CACHE_TAG SIGNED_URLS DOCKERCFG"

for v in $vars
do echo "$v: $(eval echo \"\$$v\")"; done

echo '----------'


# Determine workspace and relative CWD

test -n "$WORKSPACE" || {
  test -n "$BUILD_CODE" && {
    export WORKSPACE=/src/$BUILD_CODE
  }
}

test -n "$WORKSPACE" || {
  test -n "$BUILD_PATH" && {
    to_workspace=./$(printf -- "$BUILD_PATH" | cut -c2- | sed 's/[^/]*/../g')
    export WORKSPACE=$(cd $to_workspace && pwd)
  }
}


# Init shell

echo WORKSPACE: $WORKSPACE
echo '--------------- loading env'
test -e ../env.sh && {
  . ./../env.sh
} || {
  . $WORKSPACE/tools/build-env.sh
}


# Load args at relative location

xtra=
test ! -e ../build-args.sh || {
  xtra="$(grep '=' ../build-args.sh | sed 's/.*/--build-arg & \\/')"
}

echo "--------------- starting build '$IMAGE_NAME'"
BUILD_DATE=$(date --rfc-3339=seconds)

docker build $xtra \
		--build-arg X_DCKR_PREFIX=$ONAME \
		--build-arg X_DCKR_BASENAME=$LNAME \
		--build-arg X_DCKR_NAME=$ONAME/$LNAME \
    --build-arg X_DCKR_TAG=$DOCKER_TAG \
    --build-arg BUILD_CODE=$BUILD_CODE \
    --build-arg IMAGE_NAME=$IMAGE_NAME \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    --build-arg SCM_TYPE=$SOURCE_TYPE \
    --build-arg GIT_BRANCH=$SOURCE_BRANCH \
    --build-arg GIT_COMMIT=$GIT_SHA1 \
    --build-arg COMMIT_MSG="$COMMIT_MSG" \
    --build-arg BUILD_DATE="$BUILD_DATE" \
    \
    -t $IMAGE_NAME .


echo "--------------- tagging '$DOCKER_TAG'"

test -n "$DOCKER_TAGS" || {
  echo "Error, no Docker-Tags." >&2
  exit 1
}

echo $DOCKER_TAGS | tr -s ', ' ' ' | while read tag
do
  test -n "$tag" || continue
  echo "docker tag '$IMAGE_NAME' '$DOCKER_REPO:$tag'"
  docker tag $IMAGE_NAME $DOCKER_REPO:$tag
done

# TODO: #echo '--------------- publishing results'
#pip install couchapp
##COUCH_DB=$(  )
#mkdir -vp build/couch/build-log
#(
#  cd build/couch/build-log
#  echo '{"env":{"default":{"db":"'$COUCH_DB'"}}}'>.couchapprc
#  couchapp pushdocs
#)


# Id: x-docker/
