#!/bin/sh
docker build \
		--build-arg X_DCKR_PREFIX=bvberkum \
		--build-arg X_DCKR_BASENAME=debian-bats \
		--build-arg X_DCKR_NAME=bvberkum/debian-bats \
    --build-arg X_DCKR_TAG=$DOCKER_TAG \
    -t $IMAGE_NAME .
