#!/bin/sh
. ./../../env.sh
docker build \
		--build-arg X_DCKR_PREFIX=$ONAME \
		--build-arg X_DCKR_BASENAME=$LNAME \
		--build-arg X_DCKR_NAME=$ONAME/$LNAME \
    --build-arg X_DCKR_TAG=$DOCKER_TAG \
    -t $IMAGE_NAME .
