#!/bin/sh
set -e
case "$SOURCE_BRANCH" in

  *-treebox )
      cp -v ../../ReadMe-treebox.md ../../README.md
    ;;

#  *-bats-dev | *-bats )
#      cp -v ../../ReadMe-bats.md ../../README.md
#    ;;

#  *-docker )
#      cp -v ../../ReadMe-docker.md ../../README.md
#    ;;

  * )
      echo "Warning: no ReadMe for '$SOURCE_BRANCH' ($DOCKER_TAG)" >&2
    ;;

esac
