name: build-testbox

on:
  push:
    branches:
      - 'testbox'
    tags:
      - 'testbox-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:

          # list of Docker images to use as base name for tags
          images: |
            dotmpe/testbox

          # generate Docker tags based on the following events/attributes
          tags: |
            type=edge,branch=testbox
            type=match,pattern=testbox-v(.*),group=1
          # edge is like the dev branch, latest is pushed upon version tag
          #
          # With multi-image repo this it not really suited. 
          #type=ref,event=branch
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Buildenv
        id: buildenv
        shell: bash
        run: |
          echo -n "::set-output name=build_time::$(date --iso=min)"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}:_/testbox"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKER_IMAGE=dotmpe/testbox
            X_DCKR_BASETAG=0.0.6
            X_DCKR_COMMIT=${{ env.GITHUB_SHA }}
            X_DCKR_VERSION=0.0.6-dev
            BUILD_TIME=${{ steps.buildenv.outputs.build_time }}
